### PR TITLE
Add CLONE GEN analysis

### PR DESCRIPTION
**Pull request by glass-w**
This PR adds more analysis to the retrospective notebook with free energy vs No. CLONES (+ No. GENS).

### CODE REVIEW

**Comment by glass-w** [comment]
Functions added to this notebook that may be good to wrap into plotting functions are: 
* `_get_DDG_values()`
* `clones_and_gens()`

These probably need some cleaning up...

**Comment by jchodera** [comment]
Not sure what's being plotted when the x-axis separates by "clone number". The clones are different statistical replicates, so we shouldn't separate out by CLONE.

**Comment by jchodera** [comment]
I think we are going to have @mcwitt have the automation system in http://github.com/choderalab/covid-moonshot-infra also generate the retrospective plots for us, so we may just want to focus on sweeping the plots we want to be regularly generated into  the automation framework there.

**Comment by glass-w** [comment]
This is now addressed with [this PR](https://github.com/choderalab/covid-moonshot-infra/pull/60) in [covid-moonshot-infra](https://github.com/choderalab/covid-moonshot-infra)

**Pull request closed without merging**
